package com.vegantravels.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CABINS__TMP".
 */
public class Cabins_TMP {

    private Long id;
    private int cabinNumber;
    private int numberOfGuest;
    /** Not-null value. */
    private String guestVT_Id;
    private int paymentStatus;
    /** Not-null value. */
    private String deviceDate;
    private long CabinUniqueId;
    private long createdAt;
    private long updatedAt;

    public Cabins_TMP() {
    }

    public Cabins_TMP(Long id) {
        this.id = id;
    }

    public Cabins_TMP(Long id, int cabinNumber, int numberOfGuest, String guestVT_Id, int paymentStatus, String deviceDate, long CabinUniqueId, long createdAt, long updatedAt) {
        this.id = id;
        this.cabinNumber = cabinNumber;
        this.numberOfGuest = numberOfGuest;
        this.guestVT_Id = guestVT_Id;
        this.paymentStatus = paymentStatus;
        this.deviceDate = deviceDate;
        this.CabinUniqueId = CabinUniqueId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCabinNumber() {
        return cabinNumber;
    }

    public void setCabinNumber(int cabinNumber) {
        this.cabinNumber = cabinNumber;
    }

    public int getNumberOfGuest() {
        return numberOfGuest;
    }

    public void setNumberOfGuest(int numberOfGuest) {
        this.numberOfGuest = numberOfGuest;
    }

    /** Not-null value. */
    public String getGuestVT_Id() {
        return guestVT_Id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuestVT_Id(String guestVT_Id) {
        this.guestVT_Id = guestVT_Id;
    }

    public int getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(int paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /** Not-null value. */
    public String getDeviceDate() {
        return deviceDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceDate(String deviceDate) {
        this.deviceDate = deviceDate;
    }

    public long getCabinUniqueId() {
        return CabinUniqueId;
    }

    public void setCabinUniqueId(long CabinUniqueId) {
        this.CabinUniqueId = CabinUniqueId;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    public long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(long updatedAt) {
        this.updatedAt = updatedAt;
    }

}
