package com.vegantravels.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CABINS__TMP".
 */
public class Cabins_TMP {

    private Long id;
    private int occupancy;
    private int cabinNumber;
    private int numberOfGuest;
    /** Not-null value. */
    private String guestVT_Id;
    private long cruizeId;
    private Integer paymentStatus;
    private Long excursion;
    /** Not-null value. */
    private String deviceDate;
    private long CabinUniqueId;
    private Long createdAt;
    private Long updatedAt;

    public Cabins_TMP() {
    }

    public Cabins_TMP(Long id) {
        this.id = id;
    }

    public Cabins_TMP(Long id, int occupancy, int cabinNumber, int numberOfGuest, String guestVT_Id, long cruizeId, Integer paymentStatus, Long excursion, String deviceDate, long CabinUniqueId, Long createdAt, Long updatedAt) {
        this.id = id;
        this.occupancy = occupancy;
        this.cabinNumber = cabinNumber;
        this.numberOfGuest = numberOfGuest;
        this.guestVT_Id = guestVT_Id;
        this.cruizeId = cruizeId;
        this.paymentStatus = paymentStatus;
        this.excursion = excursion;
        this.deviceDate = deviceDate;
        this.CabinUniqueId = CabinUniqueId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getOccupancy() {
        return occupancy;
    }

    public void setOccupancy(int occupancy) {
        this.occupancy = occupancy;
    }

    public int getCabinNumber() {
        return cabinNumber;
    }

    public void setCabinNumber(int cabinNumber) {
        this.cabinNumber = cabinNumber;
    }

    public int getNumberOfGuest() {
        return numberOfGuest;
    }

    public void setNumberOfGuest(int numberOfGuest) {
        this.numberOfGuest = numberOfGuest;
    }

    /** Not-null value. */
    public String getGuestVT_Id() {
        return guestVT_Id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuestVT_Id(String guestVT_Id) {
        this.guestVT_Id = guestVT_Id;
    }

    public long getCruizeId() {
        return cruizeId;
    }

    public void setCruizeId(long cruizeId) {
        this.cruizeId = cruizeId;
    }

    public Integer getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(Integer paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public Long getExcursion() {
        return excursion;
    }

    public void setExcursion(Long excursion) {
        this.excursion = excursion;
    }

    /** Not-null value. */
    public String getDeviceDate() {
        return deviceDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceDate(String deviceDate) {
        this.deviceDate = deviceDate;
    }

    public long getCabinUniqueId() {
        return CabinUniqueId;
    }

    public void setCabinUniqueId(long CabinUniqueId) {
        this.CabinUniqueId = CabinUniqueId;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

}
