package com.vegantravels.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CABINS".
 */
public class Cabins {

    private Long id;
    private int cabinNumber;
    private int numberOfGuest;
    private int guestId;
    private int paymentStatus;
    /** Not-null value. */
    private String deviceDate;
    private long CabinUniqueId;
    private Long createdAt;
    private Long updatedAt;

    public Cabins() {
    }

    public Cabins(Long id) {
        this.id = id;
    }

    public Cabins(Long id, int cabinNumber, int numberOfGuest, int guestId, int paymentStatus, String deviceDate, long CabinUniqueId, Long createdAt, Long updatedAt) {
        this.id = id;
        this.cabinNumber = cabinNumber;
        this.numberOfGuest = numberOfGuest;
        this.guestId = guestId;
        this.paymentStatus = paymentStatus;
        this.deviceDate = deviceDate;
        this.CabinUniqueId = CabinUniqueId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCabinNumber() {
        return cabinNumber;
    }

    public void setCabinNumber(int cabinNumber) {
        this.cabinNumber = cabinNumber;
    }

    public int getNumberOfGuest() {
        return numberOfGuest;
    }

    public void setNumberOfGuest(int numberOfGuest) {
        this.numberOfGuest = numberOfGuest;
    }

    public int getGuestId() {
        return guestId;
    }

    public void setGuestId(int guestId) {
        this.guestId = guestId;
    }

    public int getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(int paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /** Not-null value. */
    public String getDeviceDate() {
        return deviceDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceDate(String deviceDate) {
        this.deviceDate = deviceDate;
    }

    public long getCabinUniqueId() {
        return CabinUniqueId;
    }

    public void setCabinUniqueId(long CabinUniqueId) {
        this.CabinUniqueId = CabinUniqueId;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

}
