package com.vegantravels.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.vegantravels.dao.CriuzeDao;
import com.vegantravels.dao.CriuzeTemporaryDao;
import com.vegantravels.dao.ExcursionDao;
import com.vegantravels.dao.ExcursionTemporaryDao;
import com.vegantravels.dao.GuestDao;
import com.vegantravels.dao.GuestTemporaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CriuzeDao.createTable(db, ifNotExists);
        CriuzeTemporaryDao.createTable(db, ifNotExists);
        ExcursionDao.createTable(db, ifNotExists);
        ExcursionTemporaryDao.createTable(db, ifNotExists);
        GuestDao.createTable(db, ifNotExists);
        GuestTemporaryDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CriuzeDao.dropTable(db, ifExists);
        CriuzeTemporaryDao.dropTable(db, ifExists);
        ExcursionDao.dropTable(db, ifExists);
        ExcursionTemporaryDao.dropTable(db, ifExists);
        GuestDao.dropTable(db, ifExists);
        GuestTemporaryDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CriuzeDao.class);
        registerDaoClass(CriuzeTemporaryDao.class);
        registerDaoClass(ExcursionDao.class);
        registerDaoClass(ExcursionTemporaryDao.class);
        registerDaoClass(GuestDao.class);
        registerDaoClass(GuestTemporaryDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
