package com.vegantravels.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.vegantravels.dao.CriuzesDao;
import com.vegantravels.dao.Criuzes_TMPDao;
import com.vegantravels.dao.Cabins_TMPDao;
import com.vegantravels.dao.Cabins_TMPDao;
import com.vegantravels.dao.ExcursionsDao;
import com.vegantravels.dao.Excursions_TMPDao;
import com.vegantravels.dao.GuestsDao;
import com.vegantravels.dao.Guests_TMPDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CriuzesDao.createTable(db, ifNotExists);
        Criuzes_TMPDao.createTable(db, ifNotExists);
        Cabins_TMPDao.createTable(db, ifNotExists);
        Cabins_TMPDao.createTable(db, ifNotExists);
        ExcursionsDao.createTable(db, ifNotExists);
        Excursions_TMPDao.createTable(db, ifNotExists);
        GuestsDao.createTable(db, ifNotExists);
        Guests_TMPDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CriuzesDao.dropTable(db, ifExists);
        Criuzes_TMPDao.dropTable(db, ifExists);
        Cabins_TMPDao.dropTable(db, ifExists);
        Cabins_TMPDao.dropTable(db, ifExists);
        ExcursionsDao.dropTable(db, ifExists);
        Excursions_TMPDao.dropTable(db, ifExists);
        GuestsDao.dropTable(db, ifExists);
        Guests_TMPDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CriuzesDao.class);
        registerDaoClass(Criuzes_TMPDao.class);
        registerDaoClass(Cabins_TMPDao.class);
        registerDaoClass(Cabins_TMPDao.class);
        registerDaoClass(ExcursionsDao.class);
        registerDaoClass(Excursions_TMPDao.class);
        registerDaoClass(GuestsDao.class);
        registerDaoClass(Guests_TMPDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
