package com.vegantravels.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.vegantravels.dao.Criuze;
import com.vegantravels.dao.Excursion;
import com.vegantravels.dao.Guest;

import com.vegantravels.dao.CriuzeDao;
import com.vegantravels.dao.ExcursionDao;
import com.vegantravels.dao.GuestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig criuzeDaoConfig;
    private final DaoConfig excursionDaoConfig;
    private final DaoConfig guestDaoConfig;

    private final CriuzeDao criuzeDao;
    private final ExcursionDao excursionDao;
    private final GuestDao guestDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        criuzeDaoConfig = daoConfigMap.get(CriuzeDao.class).clone();
        criuzeDaoConfig.initIdentityScope(type);

        excursionDaoConfig = daoConfigMap.get(ExcursionDao.class).clone();
        excursionDaoConfig.initIdentityScope(type);

        guestDaoConfig = daoConfigMap.get(GuestDao.class).clone();
        guestDaoConfig.initIdentityScope(type);

        criuzeDao = new CriuzeDao(criuzeDaoConfig, this);
        excursionDao = new ExcursionDao(excursionDaoConfig, this);
        guestDao = new GuestDao(guestDaoConfig, this);

        registerDao(Criuze.class, criuzeDao);
        registerDao(Excursion.class, excursionDao);
        registerDao(Guest.class, guestDao);
    }
    
    public void clear() {
        criuzeDaoConfig.getIdentityScope().clear();
        excursionDaoConfig.getIdentityScope().clear();
        guestDaoConfig.getIdentityScope().clear();
    }

    public CriuzeDao getCriuzeDao() {
        return criuzeDao;
    }

    public ExcursionDao getExcursionDao() {
        return excursionDao;
    }

    public GuestDao getGuestDao() {
        return guestDao;
    }

}
