package com.vegantravels.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EXCURSION".
 */
public class Excursion {

    private Long id;
    /** Not-null value. */
    private String dateFrom;
    /** Not-null value. */
    private String dateTo;
    /** Not-null value. */
    private String excursioneName;
    private long pricePerPerson;
    private int maxGuest;
    private long cruizeKey;

    public Excursion() {
    }

    public Excursion(Long id) {
        this.id = id;
    }

    public Excursion(Long id, String dateFrom, String dateTo, String excursioneName, long pricePerPerson, int maxGuest, long cruizeKey) {
        this.id = id;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.excursioneName = excursioneName;
        this.pricePerPerson = pricePerPerson;
        this.maxGuest = maxGuest;
        this.cruizeKey = cruizeKey;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDateFrom() {
        return dateFrom;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateFrom(String dateFrom) {
        this.dateFrom = dateFrom;
    }

    /** Not-null value. */
    public String getDateTo() {
        return dateTo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateTo(String dateTo) {
        this.dateTo = dateTo;
    }

    /** Not-null value. */
    public String getExcursioneName() {
        return excursioneName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExcursioneName(String excursioneName) {
        this.excursioneName = excursioneName;
    }

    public long getPricePerPerson() {
        return pricePerPerson;
    }

    public void setPricePerPerson(long pricePerPerson) {
        this.pricePerPerson = pricePerPerson;
    }

    public int getMaxGuest() {
        return maxGuest;
    }

    public void setMaxGuest(int maxGuest) {
        this.maxGuest = maxGuest;
    }

    public long getCruizeKey() {
        return cruizeKey;
    }

    public void setCruizeKey(long cruizeKey) {
        this.cruizeKey = cruizeKey;
    }

}
