package com.vegantravels.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.vegantravels.dao.ExcursionTemporary;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXCURSION_TEMPORARY".
*/
public class ExcursionTemporaryDao extends AbstractDao<ExcursionTemporary, Long> {

    public static final String TABLENAME = "EXCURSION_TEMPORARY";

    /**
     * Properties of entity ExcursionTemporary.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DateFrom = new Property(1, java.util.Date.class, "dateFrom", false, "DATE_FROM");
        public final static Property DateTo = new Property(2, java.util.Date.class, "dateTo", false, "DATE_TO");
        public final static Property ExcursioneName = new Property(3, String.class, "excursioneName", false, "EXCURSIONE_NAME");
        public final static Property PricePerPerson = new Property(4, long.class, "pricePerPerson", false, "PRICE_PER_PERSON");
        public final static Property MaxGuest = new Property(5, int.class, "maxGuest", false, "MAX_GUEST");
        public final static Property CruizeKey = new Property(6, long.class, "cruizeKey", false, "CRUIZE_KEY");
    };


    public ExcursionTemporaryDao(DaoConfig config) {
        super(config);
    }
    
    public ExcursionTemporaryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXCURSION_TEMPORARY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DATE_FROM\" INTEGER NOT NULL ," + // 1: dateFrom
                "\"DATE_TO\" INTEGER NOT NULL ," + // 2: dateTo
                "\"EXCURSIONE_NAME\" TEXT NOT NULL ," + // 3: excursioneName
                "\"PRICE_PER_PERSON\" INTEGER NOT NULL ," + // 4: pricePerPerson
                "\"MAX_GUEST\" INTEGER NOT NULL ," + // 5: maxGuest
                "\"CRUIZE_KEY\" INTEGER NOT NULL );"); // 6: cruizeKey
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXCURSION_TEMPORARY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ExcursionTemporary entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDateFrom().getTime());
        stmt.bindLong(3, entity.getDateTo().getTime());
        stmt.bindString(4, entity.getExcursioneName());
        stmt.bindLong(5, entity.getPricePerPerson());
        stmt.bindLong(6, entity.getMaxGuest());
        stmt.bindLong(7, entity.getCruizeKey());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ExcursionTemporary readEntity(Cursor cursor, int offset) {
        ExcursionTemporary entity = new ExcursionTemporary( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // dateFrom
            new java.util.Date(cursor.getLong(offset + 2)), // dateTo
            cursor.getString(offset + 3), // excursioneName
            cursor.getLong(offset + 4), // pricePerPerson
            cursor.getInt(offset + 5), // maxGuest
            cursor.getLong(offset + 6) // cruizeKey
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ExcursionTemporary entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDateFrom(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setDateTo(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setExcursioneName(cursor.getString(offset + 3));
        entity.setPricePerPerson(cursor.getLong(offset + 4));
        entity.setMaxGuest(cursor.getInt(offset + 5));
        entity.setCruizeKey(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ExcursionTemporary entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ExcursionTemporary entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
