package com.vegantravels.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GUEST".
 */
public class Guest {

    private Long id;
    /** Not-null value. */
    private String guestName;
    /** Not-null value. */
    private String cabin;
    private long guestKey;

    public Guest() {
    }

    public Guest(Long id) {
        this.id = id;
    }

    public Guest(Long id, String guestName, String cabin, long guestKey) {
        this.id = id;
        this.guestName = guestName;
        this.cabin = cabin;
        this.guestKey = guestKey;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getGuestName() {
        return guestName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }

    /** Not-null value. */
    public String getCabin() {
        return cabin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCabin(String cabin) {
        this.cabin = cabin;
    }

    public long getGuestKey() {
        return guestKey;
    }

    public void setGuestKey(long guestKey) {
        this.guestKey = guestKey;
    }

}
