package com.vegantravels.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String name;
    private int age;
    /** Not-null value. */
    private String password;
    /** Not-null value. */
    private String proPic;
    private int point;
    private boolean active;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String name, int age, String password, String proPic, int point, boolean active) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.password = password;
        this.proPic = proPic;
        this.point = point;
        this.active = active;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    /** Not-null value. */
    public String getProPic() {
        return proPic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProPic(String proPic) {
        this.proPic = proPic;
    }

    public int getPoint() {
        return point;
    }

    public void setPoint(int point) {
        this.point = point;
    }

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}
